BuildHelpers/Public/Get-BuildVariables.ps1
If a Path was supplied via param, it was ignoring it.
=> Fix #2: path always being set to $PWD.Path

BuildHelpers/BuildHelpers.psd1, BuildHelpers/BuildHelpers.psm1, BuildHelpers/Scripts/Set-BuildVariable.ps1, BuildHelpers/en-US/about_BuildHelpers.help.txt
Implemented as discussed, updated docs.
Tried to propagate coding style used in other scripts.
Not created ready to use tests.
But still tested locally.
Tested cases:
````powershell
#defaults to -Scope 1, the caller scope
Set-BuildVariable -Path $PSScriptRoot
Get-Variable BH* -Scope 0
#defaults to -Scope 0, the caller scope
. Set-BuildVariable -Path $PSScriptRoot
Get-Variable BH* -Scope 0
#sets variables in the caller script scope
. Set-BuildVariable -Path $PSScriptRoot -Scope Script
Get-Variable BH* -Scope Script
#error
Set-BuildVariable -Path $PSScriptRoot -Scope Script
````
=> Add Set-BuildVariable, resolve #10

BuildHelpers/Public/Set-ModuleFormats.ps1
Added Set-ModuleFormats function for updating module manifest with all ps1xml available in a specified folder.
This function is based on `Set-ModuleFunctions`. I've used runspaces to load the module.
Example:
Set-ModuleFormats -FormatsRelativePath '.\Format'
=> New function Set-ModuleFormat

BuildHelpers/Public/Get-ProjectName.ps1
Modifies `Get-ProjectName`, adding additional logic for handling `source` and `src` folders in project layout.
+ Resolves RamblingCookieMonster/BuildHelpers#19
This allows users who organize their projects using a `source` or `src` folder to utilize BuildHelpers.
Executed against a local project, ran the psake tests.
=> Add handling for projects w/ source folder layout

BuildHelpers/BuildHelpers.psd1, BuildHelpers/Public/Get-ProjectName.ps1
Adds a default output for `Get-ProjectName` if all other methods fail.
Updates the warning if no valid project names are discovered from looking in the project root's path and returns the project root's folder name as the project name.
Resolves RamblingCookieMonster/BuildHelpers#20
A project should return _some_ value for its name even if discovery methods fail; defaulting to the name of the project root's folder is a sane default - the function should still publish a warning to the user so they're aware of this.
Executed locally and psake tests executed successfully.
Since this causes the function to return data instead of being null, this is a backward-breaking change.
=> Add default output for Get-ProjectName

BuildHelpers/Public/Get-PSModuleManifest.ps1, BuildHelpers/Public/Get-ProjectName.ps1
+ Fixed a minor bug in the comment-based help for Get-ProjectName
+ Removed extraneous comma from Get-ProjectName
+ Added functionality to Get-PSModuleManifest to allow discovery
of manifests when the project is organized to use a source or src
folder layout.
+ Updated comment-based help for Get-PSModuleManifest to reflect
the new capability.
+ Resolves RamblingCookieMonster/BuildHelpers#23
This allows users who organize their projects using a `source` or `src` folder to utilize BuildHelpers.
Executed against a local project, ran the psake tests.
=> Ensure source folder layout works for project name and manifest

BuildHelpers/Public/Get-PSModuleManifest.ps1
+ The function was returning the basename instead of the fullname, and so the path
did not resolve properly. Fixed.
Sorry for submitting so many PRs recently, I guess I accidentally reverted the file before the previous PR - it should now return the full paths to the manifests instead of their base name.
=> Ensure Get-PSModuleManifest returns full path

BuildHelpers/Public/Add-TestResultToAppveyor.ps1, BuildHelpers/Public/Set-BuildEnvironment.ps1, BuildHelpers/Scripts/Set-BuildVariable.ps1
Hi,
This feature allows to change the prefix for the environment variable names, default is 'BH' for backward compatibility.
I've also extracted a function to upload the test results to AppVeyor, and tested that [here](https://ci.appveyor.com/project/gaelcolas/samplemodule/build/tests).
=> add environment Variable prefix as per Set-BuildVariable.ps1

BuildHelpers/Public/Set-BuildEnvironment.ps1
Sorry, you were too fast releasing (or github too slow), that second commit fixing a type did not follow...
Gael
=> fixing variable name typo

BuildHelpers/Public/Set-BuildEnvironment.ps1
When Get-BuildEnvironment runs at line 117, the BuildOutput parameter isn't passed and thus it generates the default every time, thus Set-BuildEnvironment always does $Projectpath\BuildOutput no matter what. Adding the parameter to pass through via GBEParms will preserve it and ensure it gets set correctly.
=> Preserve BuildOutput parameter through Set

BuildHelpers/Public/Get-BuildEnvironment.ps1, BuildHelpers/Public/Get-BuildVariables.ps1, BuildHelpers/Public/Invoke-Git.ps1, BuildHelpers/Public/Set-BuildEnvironment.ps1
The code was looking for the `git.exe` command by default.
That's been a problem for me as sometimes my environments only rely on ChefDK's integrated git which is `git.cmd`, and could be a problem on non windows machine as well.
I've changed the references to use `(Get-Command 'git')[0].Path` when the Git path is not specified.
There should be no breaking change, but worth doing more testing your end.
I'm also considering putting the line above directly into the Default parameters value, up to you really.
Gael
=> Removing Dependency on .exe for Git

Build/build.requirements.psd1, Build/psake.ps1, BuildHelpers/BuildHelpers.psd1, BuildHelpers/Public/Get-ModuleAliases.ps1, BuildHelpers/Public/Get-ModuleFunctions.ps1, BuildHelpers/Public/Get-NextPSGalleryVersion.ps1, BuildHelpers/Public/Set-ModuleAliases.ps1, BuildHelpers/Public/Set-ModuleFunctions.ps1
Fork reset, force push, and a few fresh commits later, now have a cleaner PR compared to #51. Repeating the motivation behind the content of each commit.
- 46cfdf7 - My module also exports aliases so ExportedCommands in Get/Set-ModuleFunctions was too broad. Modified the functions to use ExportedFunctions instead of ExportedCommands so that FunctionsToExport in the module manifest contained only functions.
- 63bbd71 - In the spirit of Get/Set-ModuleFunctions, I created Get/Set-ModuleAliases functions to manage my module manifest's AliasesToExport key. My module defines aliases for some functions by appending the New-Alias command after the function definition. So to get the aliases into my module's ExportedAliases, my module's psm1 file executes Export-ModuleMember -Alias (Get-Alias | …
=> Improvements to Module Manifest's FunctionsToExport & AliasesToExport plus Get-NextPSGalleryVersion

BuildHelpers/Public/Get-BuildVariables.ps1
This PR fixes the issue where the BHCommitMessage can end with a space in AppVeyor.
Sorry about the whitespace clean up in the file (VS Code :grin:).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ramblingcookiemonster/buildhelpers/56)
=> TrimEnd AppVeyor Commit message - Fixes #55

BuildHelpers/Public/Get-ProjectName.ps1, Tests/BuildHelpers.Tests.ps1
The capitalization of folder is lost with the way AppVeyor clones a repository.
This makes Get-ProjectName use AppVeyor's ProjectName if available
=> Uses AppVeyor Project if available

BuildHelpers/BuildHelpers.psm1
`Configuration` module which is shipped in this repository is now only
loaded when no newer version of `Configuration` could be found on the system
_personally I prefer for the `Configuration` module not to be shipped in the module, as submitted in #60._
=> Improved loading of Configuration module

BuildHelpers/BuildHelpers.psd1
Without explicitly listing aliases for export in the PSD1, they can only be used in the module scope.
This should fix any builds broken by the release that followed #72 
/cc @lipkau @RamblingCookieMonster
=> Export new aliases from #72 in PSD1

BuildHelpers/BuildHelpers.psd1, BuildHelpers/Public/Get-BuildVariable.ps1, Tests/TestData/dummymodule.psd1
This Fixes #96 and adds support for a portion of the environment variables exposed when running in a GitHub Action. Specifically:
```
$env:BHBuildSystem
$env:BHProjectPath
$env:BHBranchName
$env:BHCommitMessage
```
GitHub Actions don't currently have the concept of a build number since they can be invoked from a number of events against a repo that don't involve code commits. For this reason, `$env:BHBuildNumber` will take the fallback of `0`.
=> Add support for GitHub Action environment variables

BuildHelpers/Public/Invoke-Git.ps1
Fix to prevent the following from occurring due to $stderr sometimes being an array due to lines 124-130:
2019-03-13T16:36:28.5845108Z ##[error]Write-Error : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified 
method is not supported.
At C:\Program Files\WindowsPowerShell\Modules\BuildHelpers\2.0.7\Public\Invoke-Git.ps1:149 char:29
+                 Write-Error $stderr.trim()
+                             ~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Write-Error], ParameterBindingException
+ FullyQualifiedErrorId : CannotConvertArgument,Microsoft.PowerShell.Commands.WriteErrorCommand
=> Fix bug in Invoke-Git

BuildHelpers/Public/Get-BuildVariable.ps1
From my research all the build environments listed as supported should publish the commit hash and just in case they can't we'll try and pull it from Git
Fixes #92
=> variable for commit hash

BuildHelpers/Public/Get-BuildEnvironment.ps1, BuildHelpers/Public/Get-ProjectName.ps1, Tests/BuildHelpers.Tests.ps1
fixes #107 
In Azure Pipelines and possibly other CIs, the root directory isn't related to the project name, so existing detection methods that depend on the root directory name matching other files or folders in the repository don't work.
This adds two more cases.  First, if we find any *.psd1s in the root of the folder, that'll be the project name.  If that fails, we'll fallback to Git to get the origin URL, split it on slashes, grab the last token (which should be just the name) and then also strip out ".git" because sometimes that's part of the origin URL.
I replicated the seemingly odd behavior that if there are multiple found PSDs it will return an array, which eventually gets joined with a space, so if there's project1.psd1 and project2.psd1 found the project name will be `project1 …
=> better project name detection when CI doesn't use sensible name as root dir

BuildHelpers/Public/Get-BuildVariable.ps1
This fixes #109 and #110. 
As far as I have understood the git documentation, the path parameter for 'git log' is more like a filter to get the last commit for a specific directory or file. So here the path is it used twice and the two values may contradict each other . The current path must be set to somewhere in the git repo anyway and then - if things are as expected - the path (SYSTEM_DEFAULTWORKINGDIRECTORY) shows to the same repo again. In my case, I am having more than one artifact to deal with and the path in SYSTEM_DEFAULTWORKINGDIRECTORY does not point to the repo. The repo is in a separate folder in SYSTEM_DEFAULTWORKINGDIRECTORY.
And if the commit message could not be retrieved, we get in in line [224](https://github.com/RamblingCookieMonster/BuildHelpers/blob/8e484dc98541a957e …
=> Removing 'path' parameter from 'git log' command

BuildHelpers/Public/Get-BuildVariable.ps1
Installing Git via scoop adds a git.ps1 shim. Get-Command as currently defined picks up this shim and tries to start it as a process which fails as "not a valid win32 application". This adjustment will ensure it gets the executable specifically. Tested cross platform to Linux as well.
`Get-BuildVariable -GitPath (get-command git -commandtype application)`
=> Add compatibility for scoop git

BuildHelpers/Private/Invoke-LikeFilter.ps1, BuildHelpers/Public/Get-GitChangedFile.ps1, Tests/BuildHelpers.Tests.ps1
Lotta changes here, all for fixing #106 plus a bunch of other QOL stuff I found along the way.
This changes Get-GitChangedFile to use git diff instead of git diff-tree.  I intitally sought to perfectly replicate the functionality as existed before, but once I got into the tests file I see that it never worked the way you intended it, so it's essentially been in a bug state for the last 3 years.  So this introduces a breaking change because running it without parameters will return files whereas it didn't before, but I think that was the original intention.
(By the way, the issue was that by default diff-tree hides merge commits so you'd never see commits that were merged in.)
So let's consider this fixing that unfiled issue.
Second, I add the ability to get way more specific about what …
=> Get git changed file

BuildHelpers/Public/Get-NextNugetPackageVersion.ps1
As credentials are set in params hashtable, it needs to be removed from cmdlet find-nugetpackage other the credential parameter is supply twice and cmdlet doesn't work.
=> fix-credentials-set-multiple-time
